### ISSUE TITLE
GPIOCONTROLLERPOOL Error

### ISSUE THREAD

**Issue by Cavadus** [evadot/fbsd_gpio_py#2]
Hi,

I'm attempting to use this library to control some GPIOs on a homemade firewall running FreeBSD.

I was able install the package via pip without issue.  However, when I run the following script:
`from fbsd_gpio import GpioController

def main():
    gpioc = GpioController(1)

    for pin in gpioc:
        print(pin)

main()
`
I am met with the following error:
`Traceback (most recent call last):
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 70, in handle
    return GPIOCONTROLLERPOOL[self._unit]['handle']
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 42, in open
    if GPIOCONTROLLERPOOL[self._unit]['handle'] != -1:
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbsd_test.py", line 9, in <module>
    main()
  File "fbsd_test.py", line 6, in main
    for pin in gpioc:
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 34, in __iter__
    pin_list = self.pin_list()
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 194, in pin_list
    pin = GpioPin(i, controller=self)
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 263, in __init__
    if self._controller.pin_exists(num) == False:
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 215, in pin_exists
    self.pin_config(num)
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 82, in pin_config
    if _gpio.gpio_pin_config(self.handle, pin_cfg) != 0:
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 72, in handle
    self.open()
  File "/root/fbsd_gpio_py/fbsd_gpio/__init__.py", line 50, in open
    raise IOError
OSError`

Why is the library not detecting my GPIO controller?

**Comment by evadot** [comment]
On what board are you running this script ? Does /dev/gpioc1 exists ?
Thanks
